### ISSUE TITLE
Pridat sekciu Nejnovější 

### ISSUE THREAD

**Issue by kapitan-iglu** [koudi/plugin.video.mall.tv#1]
Dala by sa do zakladneho menu pridat aj sekcia [Nejnovější](https://www.mall.tv/sekce/nejnovejsi)? Velmi uzitocne pri vecernom: "tak co dnes pribudlo?". Ak by sa to podarilo, tak by pridanie aj sekcie [Nejsledovanější](https://www.mall.tv/sekce/nejsledovanejsi) uz nemal byt problem.

**Comment by koudi** [comment]
Nejnovější už mám, jen jsem to ještě nezabalil jako release.

https://github.com/koudi/plugin.video.mall.tv/commits/master

**Comment by koudi** [comment]
https://github.com/koudi/plugin.video.mall.tv/releases/tag/v0.0.4
